### ISSUE TITLE
Noise supression button not appearing

### ISSUE THREAD

**Issue by ari-rs** [KaylorBen/nixcord#55]
I am on nixcord latest am when in a vc the noise suppression button is not there and there is no noise suppressions working

![PXL_20241115_234110593](https://github.com/user-attachments/assets/b65375a9-5959-40ab-8673-96c58904af0a)
![PXL_20241115_234122132 MP](https://github.com/user-attachments/assets/5deba8ab-6f77-41af-bb8c-76bc168f907f)

**Comment by ari-rs** [comment]
How come vencord and vesktop are not afflicted by this problem and only nixcord?

**Comment by Soikr** [comment]
> How come vencord and vesktop are not afflicted by this problem and only nixcord?

@ari-rs Vesktop is basically a webpage so tampering detection would be weird. I dont know what vencord itself does that allows it to go undetected but this problem is exclusively on nix, not directly a nixcord issue. https://github.com/NixOS/nixpkgs/issues/195512

**Comment by kibiz0r** [comment]
Just popped my head in from a separate issue, but noticed I can offer a little piece of my (still very immature, so take with a grain of salt) knowledge of NixOS here:

> How come vencord and vesktop are not afflicted by this problem and only nixcord?

@ari-rs Because of how NixOS sandboxes executables to explicitly manage dependencies, it has the modify the Discord binary to inject the correct environment into it or else Discord would fall on its face because basically *nothing* exists globally in the OS.

Tampering with the binary that way causes Krisp's DRM to think the plugin has been hijacked into a different app.

I'm not actually familiar with Vencord (sorry for trespassing!) but I assume it probably doesn't modify the original binary.
